---
apiVersion: v1
kind: Service
metadata:
  annotations:
    api.service.kubernetes.io/path: /services/testConnection
    fabric8.io/git-commit: 3ce888e08119850e916cb435e7ec19de916c1813
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    app: spring-boot-cxf-jaxrs
    provider: fabric8
    version: 1.0-SNAPSHOT
    group: io.fabric8.quickstarts.cxf.jaxrs
  name: spring-boot-cxf-jaxrs
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-cxf-jaxrs
    provider: fabric8
    group: io.fabric8.quickstarts.cxf.jaxrs
